[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = -ra --strict-markers --cov=documents --cov=users --cov=config --cov-report=term-missing --cov-fail-under=75
